name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          PI_USER: pi
          PI_HOST: ${{ secrets.PI_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          ssh-keyscan -H "$PI_HOST" >> ~/.ssh/known_hosts
          
          ssh $PI_USER@$PI_HOST << 'EOF'
            set -e  # Stop jeśli wystąpi błąd
            cd ~/app
          
            git fetch origin main
            if [ "$(git rev-parse HEAD)" != "$(git rev-parse @{u})" ]; then
              echo "Zmiany wykryte, wdrażanie..."
              git pull origin main
              npm install --production
              npm run build
              pm2 restart app || pm2 start npm --name "app" -- start
              echo "Deployment zakończony!"
            else
              echo "Brak zmian, deployment pominięty."
            fi
          EOF
