name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          PI_USER: ubuntu
          PI_HOST: ${{ secrets.PI_HOST }}
        run: |
          # Uruchomienie ssh-agent
          eval $(ssh-agent -s)
          
          # Utworzenie katalogu ~/.ssh, jeśli nie istnieje
          mkdir -p ~/.ssh
          
          # Poprawne przekazanie klucza
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-add ~/.ssh/deploy_key
          
          # Zaufanie do hosta
          ssh-keyscan -H "$PI_HOST" >> ~/.ssh/known_hosts
          
          # SSH do Raspberry Pi i deployment
          ssh $PI_USER@$PI_HOST << 'EOF'
            set -e
            cd ~/app
            git pull origin main
            npm install --production
            npm run build
            pm2 restart app || pm2 start npm --name "app" -- start
          EOF
