name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          PI_USER: pi
          PI_HOST: ${{ secrets.PI_HOST }}
        run: |
          eval $(ssh-agent -s)

          mkdir -p ~/.ssh

          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

          ssh-keyscan -H "$PI_HOST" >> ~/.ssh/known_hosts

          ssh $PI_USER@$PI_HOST << 'EOF'
            set -e
            cd ~/app
            git pull origin main
            npm install --production
            npm run build
            pm2 restart app || pm2 start npm --name "app" -- start
          EOF
      
