name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          PI_USER: pi
          PI_HOST: 192.168.68.121
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $PI_USER@$PI_HOST << 'EOF'
            cd /home/pi/app
            git pull origin main
            npm install
            npm run build
            pm2 restart app
          EOF
